"""add universe membership table

Revision ID: 673305a68774
Revises: ab68fa156fda
Create Date: 2026-10-04 19:36:08.457162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '673305a68774'
down_revision: Union[str, Sequence[str], None] = 'ab68fa156fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universe_membership',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('entered_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('exited_on', sa.DateTime(timezone=True), nullable=True),
    sa.Column('median_dollar_volume', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('threshold_usd', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.CheckConstraint('exited_on IS NULL OR exited_on > entered_on', name=op.f('ck_universe_membership_exit_after_entry')),
    sa.CheckConstraint('median_dollar_volume >= 0', name=op.f('ck_universe_membership_volume_non_negative')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], name=op.f('fk_universe_membership_instrument_id_instrument'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_universe_membership'))
    )
    op.create_index('ix_universe_membership_entered_exited', 'universe_membership', ['entered_on', 'exited_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_universe_membership_entered_exited', table_name='universe_membership')
    op.drop_table('universe_membership')
    # ### end Alembic commands ###
