"""extend derivative stats and drop liquidation

Revision ID: 69f75ad34814
Revises: d1b0beca00af
Create Date: 2026-10-03 23:55:11.821147

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69f75ad34814'
down_revision: Union[str, Sequence[str], None] = 'd1b0beca00af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_liquidation_instrument_id_ts'), table_name='liquidation')
    op.drop_table('liquidation')
    # Postgres keeps an enum type after its table is dropped. Alembic never
    # autogenerates this, so the type would linger and the downgrade below would
    # only work by accident, relying on the leftover.
    sa.Enum(name='liquidation_side').drop(op.get_bind(), checkfirst=True)
    op.add_column('derivative_stat', sa.Column('open_interest_value', sa.Numeric(precision=28, scale=12), nullable=True))
    op.add_column('derivative_stat', sa.Column('toptrader_long_short_account_ratio', sa.Numeric(precision=18, scale=12), nullable=True))
    op.add_column('derivative_stat', sa.Column('toptrader_long_short_position_ratio', sa.Numeric(precision=18, scale=12), nullable=True))
    op.add_column('derivative_stat', sa.Column('taker_long_short_volume_ratio', sa.Numeric(precision=18, scale=12), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('derivative_stat', 'taker_long_short_volume_ratio')
    op.drop_column('derivative_stat', 'toptrader_long_short_position_ratio')
    op.drop_column('derivative_stat', 'toptrader_long_short_account_ratio')
    op.drop_column('derivative_stat', 'open_interest_value')
    sa.Enum('long', 'short', name='liquidation_side').create(
        op.get_bind(), checkfirst=True
    )
    op.create_table('liquidation',
    sa.Column('id', sa.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('ts', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    # create_type=False: the type is created explicitly above. Without this,
    # create_table emits a second CREATE TYPE with no existence check and the
    # downgrade fails with DuplicateObject.
    sa.Column('side', postgresql.ENUM('long', 'short', name='liquidation_side', create_type=False), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.NUMERIC(precision=28, scale=12), autoincrement=False, nullable=False),
    sa.Column('price', sa.NUMERIC(precision=28, scale=12), autoincrement=False, nullable=False),
    sa.CheckConstraint('quantity > 0::numeric', name=op.f('ck_liquidation_quantity_positive')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], name=op.f('fk_liquidation_instrument_id_instrument'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_liquidation'))
    )
    op.create_index(op.f('ix_liquidation_instrument_id_ts'), 'liquidation', ['instrument_id', 'ts'], unique=False)
    # ### end Alembic commands ###
