"""add corporate action table

Revision ID: a4d3b0a74c37
Revises: 673305a68774
Create Date: 2026-10-04 20:17:52.424145

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4d3b0a74c37'
down_revision: Union[str, Sequence[str], None] = '673305a68774'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('corporate_action',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('effective_on', sa.DateTime(timezone=True), nullable=False),
    sa.Column('action_type', sa.Enum('reverse_split', 'forward_split', 'unit_split', 'spin_off', 'stock_merger', name='corporate_action_type'), nullable=False),
    sa.Column('ratio', sa.Numeric(precision=18, scale=12), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.CheckConstraint('ratio IS NULL OR ratio > 0', name=op.f('ck_corporate_action_ratio_positive')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], name=op.f('fk_corporate_action_instrument_id_instrument'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_corporate_action')),
    sa.UniqueConstraint('instrument_id', 'effective_on', 'action_type', name=op.f('uq_corporate_action_instrument_id_effective_on_action_type'))
    )
    op.create_index('ix_corporate_action_effective_on', 'corporate_action', ['effective_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_corporate_action_effective_on', table_name='corporate_action')
    op.drop_table('corporate_action')
    # Postgres keeps an enum type after its table is dropped; Alembic never
    # autogenerates this, so the downgrade would leave it orphaned and a later
    # upgrade would fail with "type already exists".
    sa.Enum(name='corporate_action_type').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
