"""add cross instrument candle scan index

Revision ID: ab68fa156fda
Revises: 3d8a17c5a9b5
Create Date: 2026-10-04 19:31:01.589785

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ab68fa156fda'
down_revision: Union[str, Sequence[str], None] = '3d8a17c5a9b5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_candle_timeframe_ts', 'candle', ['timeframe', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_candle_timeframe_ts', table_name='candle')
    # ### end Alembic commands ###
