"""create market data tables

Revision ID: d1b0beca00af
Revises: 
Create Date: 2026-10-03 23:08:45.203715

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd1b0beca00af'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('symbol', sa.String(length=32), nullable=False),
    sa.Column('venue', sa.String(length=32), nullable=False),
    sa.Column('asset_class', sa.Enum('crypto', 'equity', name='asset_class'), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_instrument')),
    sa.UniqueConstraint('venue', 'symbol', name=op.f('uq_instrument_venue_symbol'))
    )
    op.create_index('ix_instrument_asset_class_is_active', 'instrument', ['asset_class', 'is_active'], unique=False)
    op.create_table('source_health',
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('consecutive_failures', sa.Integer(), server_default=sa.text('0'), nullable=False),
    sa.PrimaryKeyConstraint('source', name=op.f('pk_source_health'))
    )
    op.create_table('candle',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('timeframe', sa.String(length=4), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('open', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('high', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('low', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('close', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('volume', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.CheckConstraint("timeframe IN ('1h', '4h', '1d')", name=op.f('ck_candle_timeframe_allowed')),
    sa.CheckConstraint('high >= low', name=op.f('ck_candle_high_ge_low')),
    sa.CheckConstraint('volume >= 0', name=op.f('ck_candle_volume_non_negative')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], name=op.f('fk_candle_instrument_id_instrument'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', 'timeframe', 'ts', name=op.f('pk_candle'))
    )
    op.create_table('catalyst',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('headline', sa.Text(), nullable=False),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('dedupe_key', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], name=op.f('fk_catalyst_instrument_id_instrument'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_catalyst')),
    sa.UniqueConstraint('dedupe_key', name=op.f('uq_catalyst_dedupe_key'))
    )
    op.create_index('ix_catalyst_instrument_id_ts', 'catalyst', ['instrument_id', 'ts'], unique=False)
    op.create_table('derivative_stat',
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('funding_rate', sa.Numeric(precision=18, scale=12), nullable=True),
    sa.Column('open_interest', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.Column('mark_price', sa.Numeric(precision=28, scale=12), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], name=op.f('fk_derivative_stat_instrument_id_instrument'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('instrument_id', 'ts', name=op.f('pk_derivative_stat'))
    )
    op.create_table('liquidation',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('side', sa.Enum('long', 'short', name='liquidation_side'), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.Column('price', sa.Numeric(precision=28, scale=12), nullable=False),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_liquidation_quantity_positive')),
    sa.ForeignKeyConstraint(['instrument_id'], ['instrument.id'], name=op.f('fk_liquidation_instrument_id_instrument'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_liquidation'))
    )
    op.create_index('ix_liquidation_instrument_id_ts', 'liquidation', ['instrument_id', 'ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_liquidation_instrument_id_ts', table_name='liquidation')
    op.drop_table('liquidation')
    op.drop_table('derivative_stat')
    op.drop_index('ix_catalyst_instrument_id_ts', table_name='catalyst')
    op.drop_table('catalyst')
    op.drop_table('candle')
    op.drop_table('source_health')
    op.drop_index('ix_instrument_asset_class_is_active', table_name='instrument')
    op.drop_table('instrument')
    # Postgres keeps enum types after their tables are dropped, so the
    # downgrade must remove them explicitly or a re-run fails on
    # "type already exists". Alembic never autogenerates this.
    sa.Enum(name='liquidation_side').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='asset_class').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
